WebApp/Controllers/JustificacionController.cs
using DataAccess.Administracion;
using Entidades.Administracion;
using SqlDataAccess.Administracion;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;

namespace WebApp.Controllers
{
    public class JustificacionController : BaseController
    {
        IJustificacionDAO justificacionDAO = new JustificacionDAO();
        IAsistenciaDAO asistenciaDAO = new AsistenciaDAO();

        // GET: Faltas y Atrasos
        [AppAuthorize("00017")]
        public ActionResult Index()
        {
            string mensaje = string.Empty;
            DataTable dt = asistenciaDAO.getAllAsistencia(ref mensaje);

            string facultadid = Utils.Utils.GetClaim("FacultadID");

            DataView view = dt.DefaultView;
            view.RowFilter = "FacultadID = " + facultadid;
            ViewBag.Faltas = view.ToTable();
            return View();
        }

        // GET: Faltas y Atrasos Justificados
        [AppAuthorize("00039")]
        public ActionResult IndexEstados()
        {
            string mensaje = string.Empty;
            DataTable dt = asistenciaDAO.getAllAsistenciaEstados(ref mensaje);

            string facultadid = Utils.Utils.GetClaim("FacultadID");

            DataView view = dt.DefaultView;
            view.RowFilter = "FacultadID = " + facultadid;
            ViewBag.Faltas = view.ToTable();
            return View();
        }

        // GET: Justificacion/Create
        [AppAuthorize("00026")]
        public ActionResult Justificar(int asistencia)
        {
            Justificacion justificacion = new Justificacion();
            justificacion.AsistenciaID = asistencia;
            return View(justificacion);
        }

        // POST: Justificacion/Create
        [HttpPost]
        [AppAuthorize("00026")]
        public ActionResult Justificar(HttpPostedFileBase Archivo, int AsistenciaID, string Comentario)
        {
            string mensaje = string.Empty;
            Justificacion justificacion = new Justificacion();

            try
            {
                if (Archivo != null)
                {
                    if(Archivo.ContentLength <= 4194304)
                    {
                        string extension = Path.GetExtension(Archivo.FileName);
                        if (extension.ToUpper() == ".PDF")
                        {
                            using (Stream inputStream = Archivo.InputStream)
                            {
                                MemoryStream memoryStream = inputStream as MemoryStream;
                                if (memoryStream == null)
                                {
                                    memoryStream = new MemoryStream();
                                    inputStream.CopyTo(memoryStream);
                                }
                                justificacion.Archivo = memoryStream.ToArray();
                            }
                            justificacion.AsistenciaID = AsistenciaID;
                            justificacion.Comentario = Comentario;
                            justificacionDAO.insertJustificacion(justificacion, GetApplicationUser(), ref mensaje);
                            if (mensaje == "OK")
                            {
                                Success("Justificación registrada con éxito", "Justificación", true);
                                return RedirectToAction("Index");
                            }
                            else
                            {
                                Warning(mensaje, "Justificación", true);
                            }
                        }
                        else
                            Warning("La extensión del archivo debe ser PDF", "Justificación", true);
                    }
                    else
                        Warning("El archivo no debe ser superior a 4 MB", "Justificación", true);
                }
                else
                    Warning("El archivo es requerido", "Justificación", true);
            }
            catch (Exception ex)
            {
                Warning(ex.Message, "Justificación", true);
            }
            return View(justificacion);
        }

        // GET: Justificacion/Descargar
        [AppAuthorize("00027")]
        public ActionResult Descargar(int asistencia)
        {
            string mensaje = string.Empty;
            Justificacion justificacion = justificacionDAO.getJustificacionByAsistencia(asistencia, ref mensaje);
            if (mensaje == "OK")
            {
                return File(justificacion.Archivo, System.Net.Mime.MediaTypeNames.Application.Octet, "Justificacion_" + justificacion.AsistenciaID + ".pdf");
            }
            else
            {
                Warning(mensaje, "Justificación", true);
                return View();
            }
        }


        // GET: JustificacionAtraso/Create
        [AppAuthorize("00036")]
        public ActionResult JustificarAtraso(int asistencia)
        {
            Justificacion justificacion = new Justificacion();
            justificacion.AsistenciaID = asistencia;
            return View(justificacion);
        }

        // POST: JustificacionAtraso/Create
        [HttpPost]
        [AppAuthorize("00036")]
        public ActionResult JustificarAtraso(int AsistenciaID, string Comentario)
        {
            string mensaje = string.Empty;
            Justificacion justificacion = new Justificacion();

            try
            {

                justificacion.AsistenciaID = AsistenciaID;
                justificacion.Comentario = Comentario;
                justificacionDAO.insertJustificacionAtraso(justificacion, GetApplicationUser(), ref mensaje);
                if (mensaje == "OK")
                {
                    Success("Justificación registrada con éxito", "Justificación", true);
                    return RedirectToAction("Index");
                }
                else
                {
                    Warning(mensaje, "Justificación de Atraso", true);
                }

            }
            catch (Exception ex)
            {
                Warning(ex.Message, "Justificación", true);
            }
            return View(justificacion);
        }
    }
}

WebApp/Views/Justificacion/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Master.cshtml";
    System.Data.DataTable dt = ViewBag.Faltas;

}


<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Listado de Faltas y Atrasos</h2>
                <style>
                    .tmbbtn {
                        width: 125px;
                    }
                </style>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>
                                Fecha
                            </th>
                            <th>
                                Usuario
                            </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (System.Data.DataRow item in dt.Rows)
                            {

                                if (char.Parse(item["Estado"].ToString()) == 'F' || char.Parse(item["Estado"].ToString()) == 'A')
                                {
                                    <tr>
                                        <td>
                                            @Html.Raw(DateTime.Parse(item["Fecha"].ToString()).ToShortDateString())
                                        </td>
                                        <td>
                                            @Html.Raw(item["Usuario"])
                                        </td>
                                        <td>

                                            @if (char.Parse(item["Estado"].ToString()) == 'F')
                                            {
                                                <a href="@Url.Action("Justificar","Justificacion", new { asistencia = item["AsistenciaID"] })" class="tmbbtn btn btn-danger">Justificar Falta</a>
                                            }
                                            @if (char.Parse(item["Estado"].ToString()) == 'A')
                                            {
                                                <a  href="@Url.Action("JustificarAtraso","Justificacion", new { asistencia = item["AsistenciaID"] })" class="tmbbtn btn btn-warning">Justificar Atraso</a>
                                            }

                                        </td>
                                    </tr>
                                }

                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

WebApp/Views/Justificacion/IndexEstados.cshtml
@{
    ViewBag.Title = "IndexEstados";
    Layout = "~/Views/Shared/_Master.cshtml";
    System.Data.DataTable dtEstados = ViewBag.Faltas;
}

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Listado de Faltas y Atrasos Justificados</h2>

                <style>
                    .tmbbtn {
                        width: 150px;
                    }
                </style>

                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>
                                Fecha
                            </th>
                            <th>
                                Usuario
                            </th>
                            <th>
                                Comentario
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (System.Data.DataRow item in dtEstados.Rows)
                        {

                            if (char.Parse(item["Estado"].ToString()) == 'J' || char.Parse(item["Estado"].ToString()) == 'K')
                            {
                                <tr>
                                    <td>
                                        @Html.Raw(DateTime.Parse(item["Fecha"].ToString()).ToShortDateString())
                                    </td>
                                    <td>
                                        @Html.Raw(item["Usuario"])
                                    </td>
                                    <td>
                                        @Html.Raw(item["Comentario"])
                                    </td>
                                    <td>
                                        @if (char.Parse(item["Estado"].ToString()) == 'J')
                                        {
                                            <a href="@Url.Action("Descargar","Justificacion", new { asistencia = item["AsistenciaID"] })" class="tmbbtn btn btn-success"><span class="glyphicon glyphicon-download-alt"></span> Falta Justificada</a>
                                        }
                                        @if (char.Parse(item["Estado"].ToString()) == 'K')
                                        {
                                            <a class="tmbbtn btn btn-success"  disabled="true"> <span class="glyphicon glyphicon-ok-circle"></span> Atraso Justificado</a>
                                        }
                                    </td>
                                </tr>
                            }

                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

WebApp/Views/Justificacion/Justificar.cshtml
@model Entidades.Administracion.Justificacion

@{
    ViewBag.Title = "Justificar";
    Layout = "~/Views/Shared/_Master.cshtml";
}
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Nueva Justificación</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                @using (Html.BeginForm("Justificar", "Justificacion", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal form-label-left" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.AsistenciaID)

                        <div class="form-group">
                            @Html.LabelFor(model => model.Comentario, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.EditorFor(model => model.Comentario, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12" } })
                                @Html.ValidationMessageFor(model => model.Comentario, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Archivo, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="file" id="Archivo" name="Archivo" class="form-control col-md-7 col-xs-12" />
                                @Html.ValidationMessageFor(model => model.Archivo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button type="submit" class="btn btn-primary">
                                    <span class="glyphicon glyphicon-floppy-disk"></span> Grabar
                                </button>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<div>
    @Html.ActionLink("Listado de Justificaciones", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApp/Views/Justificacion/JustificarAtraso.cshtml
@model Entidades.Administracion.Justificacion

@{
    ViewBag.Title = "JustificarAtraso";
    Layout = "~/Views/Shared/_Master.cshtml";
}
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Nueva Justificación de Atraso</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                @using (Html.BeginForm("JustificarAtraso", "Justificacion", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal form-label-left" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.AsistenciaID)

                        <div class="form-group">
                            @Html.LabelFor(model => model.Comentario, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.EditorFor(model => model.Comentario, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12" } })
                                @Html.ValidationMessageFor(model => model.Comentario, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button type="submit" class="btn btn-primary">
                                    <span class="glyphicon glyphicon-floppy-disk"></span> Aprobar
                                </button>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<div>
    @Html.ActionLink("Listado de Justificaciones", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}