WebApp/Controllers/BaseController.cs
using DataAccess.Administracion;
using Entidades.Administracion;
using Entidades.Utils;
using SqlDataAccess.Administracion;
using SqlDataAccess.Seguridad;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class BaseController: Controller
    {
        IAppMenuDAO appmenuDAO = new AppMenuDAO();

        public string GetApplicationUser()
        {
            return User.Identity.Name;
        }

        public string GetApplicationUserID()
        {
            return User.Identity.Name;
        }

        public ActionResult Menu()
        {
            if (Request.IsAuthenticated)
            {
                var claimsIdentity = ClaimsPrincipal.Current.Identities.FirstOrDefault();
                var aux = claimsIdentity.Claims.FirstOrDefault(c => c.Type == "RolID");
                string mensaje = string.Empty;
                List<AppMenu> menus = appmenuDAO.getAllbyRol(int.Parse(aux.Value), ref mensaje);
                return PartialView("_Menu", menus);
            }
            return null;
        }

        public void Success(string message, string titulo, bool dismissable = false)
        {
            AddAlert(AlertStyles.Success, message, titulo, dismissable);
        }

        public void Information(string message, string titulo, bool dismissable = false)
        {
            AddAlert(AlertStyles.Information, message, titulo, dismissable);
        }

        public void Warning(string message, string titulo, bool dismissable = false)
        {
            AddAlert(AlertStyles.Warning, message, titulo, dismissable);
        }

        public void Danger(string message, string titulo, bool dismissable = false)
        {
            AddAlert(AlertStyles.Danger, message, titulo, dismissable);
        }

        private void AddAlert(string alertStyle, string message, string titulo, bool dismissable)
        {
            var alerts = TempData.ContainsKey(Alert.TempDataKey)
                ? (List<Alert>)TempData[Alert.TempDataKey]
                : new List<Alert>();

            alerts.Add(new Alert
            {
                AlertStyle = alertStyle,
                Message = message,
                Dismissable = dismissable,
                Titulo = titulo
            });

            TempData[Alert.TempDataKey] = alerts;
        }

    }
}

WebApp/Controllers/InstitucionController.cs
using DataAccess.Administracion;
using Entidades.Administracion;
using SqlDataAccess.Administracion;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class InstitucionController : BaseController
    {
        IInstitucionDAO institucionDAO = new InstitucionDAO();

        // GET: Institucion
        public ActionResult Index()
        {
            string mensaje = string.Empty;
            List<Institucion> instituciones = institucionDAO.getAllInstitucion(ref mensaje);
            if (mensaje != "OK")
                return View();
            else
                return View(instituciones);
        }

        // GET: Institucion/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Institucion/Create
        [HttpPost]
        public ActionResult Create(Institucion institucion)
        {
            try
            {
                string mensaje = string.Empty;
                institucionDAO.insertInstitucion(institucion, GetApplicationUser(), ref mensaje);
                if (mensaje == "OK")
                    return RedirectToAction("Index");
                else
                    return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Institucion/Edit/5
        public ActionResult Edit(int id)
        {
            Institucion institucion = null;
            string mensaje = string.Empty;
            institucion = institucionDAO.getInstitucion(id, ref mensaje);
            return View(institucion);
        }

        // POST: Institucion/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Institucion institucion)
        {
            try
            {
                string mensaje = string.Empty;
                institucionDAO.updateInstitucion(institucion, GetApplicationUser(), ref mensaje);
                if (mensaje == "OK")
                    return RedirectToAction("Index");
                else
                    return View();
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Instituciones()
        {
            string mensaje = string.Empty;
            List<Institucion> instituciones = institucionDAO.getAllInstitucion(ref mensaje);
            if (mensaje != "OK")
                return View();
            else
                return PartialView("_Instituciones", instituciones.Where(p => p.Estado && p.Estado));
        }

        [HttpPost]
        public JsonResult ConsultarInstitucion(int id)
        {
            try
            {
                string mensaje = string.Empty;
                var institucion = institucionDAO.getInstitucion(id, ref mensaje);
                return Json(new { institucion = institucion, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { mensaje = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

WebApp/Views/Shared/_Alerts.cshtml
@{
    var alerts = TempData.ContainsKey(Entidades.Utils.Alert.TempDataKey)
                ? (List<Entidades.Utils.Alert>)TempData[Entidades.Utils.Alert.TempDataKey]
                : new List<Entidades.Utils.Alert>();
}
@{if (alerts.Any())
    {
        foreach (var item in alerts)
        {
            switch (item.AlertStyle)
            {
                case Entidades.Utils.AlertStyles.Warning:
                    <script type="text/javascript">
                        new PNotify({
                            title: '@item.Titulo',
                            text: '@item.Message',
                            type: 'info',
                            styling: 'bootstrap3',
                            delay: 4000
                        });
                    </script>
                    break;
                case Entidades.Utils.AlertStyles.Danger:
                    <script type="text/javascript">
                        new PNotify({
                            title: '@item.Titulo',
                            text: '@item.Message',
                            type: 'error',
                            styling: 'bootstrap3',
                            delay: 4000
                        });
                    </script>
                    break;
                case Entidades.Utils.AlertStyles.Success:
                    <script type="text/javascript">
                        new PNotify({
                            title: '@item.Titulo',
                            text: '@item.Message',
                            type: 'success',
                            styling: 'bootstrap3',
                            delay: 4000
                        });
                    </script>
                    break;
            }
        }
    }
}

WebApp/Views/Shared/_Instituciones.cshtml
@model IEnumerable<Entidades.Administracion.Institucion>

<div class="modal fade ModalInstituciones in" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">Instituciones</h4>
            </div>
            <div class="modal-body">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th></th>
                            <th>
                                @Html.DisplayNameFor(model => model.RazonSocial)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Ruc)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.RepresentanteLegal)
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <a class="btn btn-primary" onclick="Instituciones(@(item.InstitucionID))">
                                        <span class="glyphicon glyphicon-pushpin"></span>
                                    </a>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.RazonSocial)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Ruc)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.RepresentanteLegal)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



<div class="modal fade" id="ModalInstituciones" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
    <div class="modal-dialog" style="width:80%">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h3> Instituciones</h3>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index","Facultad")">Facultades</a></li>
                    <li><a href="@Url.Action("Index","Carrera")">Carreras</a></li>
                    <li><a href="@Url.Action("Index","Pasante")">Pasantes</a></li>
                    <li><a href="@Url.Action("Index","Tutor")">Tutores</a></li>
                    <li><a href="@Url.Action("Index","Institucion")">Instituciones</a></li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />

        <footer>
            <p>&copy; @DateTime.Now.Year - CINT</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/datatables")
    @Scripts.Render("~/bundles/jqueryval")
    <script src="../Scripts/Layout.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_Master.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Expires" content="0" />
    <meta http-equiv="Pragma" content="no-cache" />
    <title>@ViewBag.Title - CINT</title>
    <!-- Bootstrap -->
    <link href="../../vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    @Styles.Render("~/Content/css")
    <!-- Font Awesome -->
    <link href="../../vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- Datatables-->
    <link href="../../vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <!-- PNotify -->
    <link href="../vendors/pnotify/dist/pnotify.custom.min.css" rel="stylesheet">
    <!--Custom Theme Style -->
    <link href="../../Content/custom.min.css" rel="stylesheet">
    <script language="javascript" type="text/javascript">
        javascript: window.history.forward(1);
    </script>
</head>
<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0; background-color:#EDEDED; text-align:center">
                        <a href="@Url.Action("Index", "Home")" class="site_title" style="padding:0px;"><img src="~/Content/img/logo_UG.png" style="width:160px; height:35px;" /></a>
                    </div>
                    <div class="clearfix"></div>
                    <style>
                        footer {
                            margin-top: -1.5%;
                        }
                    </style>

                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <ul class="nav side-menu">
                                @Html.Action("Menu", "Base")
                            </ul>
                        </div>

                    </div>
                    <!-- /sidebar menu -->

                </div>
            </div>
            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <nav>
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>
                        <ul class="nav navbar-nav navbar-right">
                            @Html.Partial("_LoginPartial")
                            <li role="presentation" class="dropdown">
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->
            <!-- page content -->
            <div class="right_col" role="main">
                <br />
                <div class="">
                    @RenderBody()
                </div>
            </div>
            <!-- /page content -->
            <!-- footer content -->
            <footer>
                <div class="pull-right">
                    <p>&copy; @DateTime.Now.Year - UG</p>
                </div>
                <div class="clearfix"></div>
            </footer>
            <!-- /footer content -->

        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/fileUpload")
    @Scripts.Render("~/bundles/jqueryval")
    <!-- FastClick -->
    <script src="../../../../vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="../../vendors/nprogress/nprogress.js"></script>
    <!-- iCheck -->
    <script src="../../vendors/iCheck/icheck.min.js"></script>
    <!-- Datatables -->
    <script src="../../vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="../../vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <!-- PNotify -->
    <script src="../vendors/pnotify/dist/pnotify.custom.min.js"></script>
    <!-- Custom Theme Scripts -->
    <script src="../../Scripts/custom.min.js"></script>
    <script src="../../Scripts/Layout.js"></script>

    @RenderSection("scripts", required: false)
    @{Html.RenderPartial("_Alerts"); }
</body>
</html>

WebApp/Views/Shared/_Menu.cshtml
@model IEnumerable<Entidades.Administracion.AppMenu>
@using Entidades.Administracion;
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    
    foreach (AppMenu padre in Model.Where(x => x.PadreID == "0"))
    {
        <li>
            <a>@padre.Titulo <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
                @foreach (AppMenu hijo in Model.Where(y => y.PadreID == padre.VistaID))
                {
                    if (hijo.Orden > 0 && !string.IsNullOrEmpty(hijo.Titulo))
                    {
                        <li><a href="@Url.Action(hijo.Vista,hijo.Controlador)">@hijo.Titulo</a></li>
                    }
                }
            </ul>
        </li>
    }
}

WebApp/Views/Shared/_Pasantes.cshtml
@model IEnumerable<Entidades.Administracion.Persona>
<div class="modal fade ModalPasantes in" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">Pasantes</h4>
            </div>
            <div class="modal-body">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th></th>
                            <th>
                                @Html.DisplayNameFor(model => model.NumeroIdentificacion)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.PrimerNombre)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.SegundoNombre)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ApellidoPaterno)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ApellidoMaterno)
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <a class="btn btn-primary" onclick="Pasantes(@(item.PersonaID))">
                                        <span class="glyphicon glyphicon-pushpin"></span>
                                    </a>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NumeroIdentificacion)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PrimerNombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SegundoNombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ApellidoPaterno)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ApellidoMaterno)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

WebApp/Views/Shared/_Tutores.cshtml
@model IEnumerable<Entidades.Administracion.Persona>
<div class="modal fade ModalTutores in" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">Tutores</h4>
            </div>
            <div class="modal-body">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th></th>
                            <th>
                                @Html.DisplayNameFor(model => model.NumeroIdentificacion)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.PrimerNombre)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.SegundoNombre)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ApellidoPaterno)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ApellidoMaterno)
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <a class="btn btn-primary" onclick="Tutores(@(item.PersonaID))">
                                        <span class="glyphicon glyphicon-pushpin"></span>
                                    </a>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NumeroIdentificacion)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PrimerNombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SegundoNombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ApellidoPaterno)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ApellidoMaterno)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>